AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - org.example::java-lambda
Parameters:
  Environment:
    Type: String
    Description: Environment name
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  DdbTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub tutorial-dynamodb-cicd-${Environment}
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      ProvisionedThroughput:
        ReadCapacityUnits: 0
        WriteCapacityUnits: 0
  JavaLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub sam-function-example-${Environment}
      Handler: org.example.StreamLambdaHandler::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Sid: DynamoDBPolicy
              Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource:
                - !GetAtt DdbTable.Arn
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  JavaLambdaApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/weather'
    Export:
      Name: JavaLambdaApi
